# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_v4.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdata_v4.proto\x12\x02v4\"\x9d\x01\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x05\x12#\n\x06status\x18\x05 \x01(\x0e\x32\x13.v4.KeyValue.Status\x12\x0f\n\x07version\x18\n \x01(\x05\"/\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0c\n\x08\x41RCHIVED\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_v4_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEYVALUE._serialized_start=22
  _KEYVALUE._serialized_end=179
  _KEYVALUE_STATUS._serialized_start=132
  _KEYVALUE_STATUS._serialized_end=179
# @@protoc_insertion_point(module_scope)
